// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/sqlight.proto

package xlight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorType int32

const (
	OperatorType_Plus     OperatorType = 0
	OperatorType_Minus    OperatorType = 1
	OperatorType_Multiply OperatorType = 2
	OperatorType_Divide   OperatorType = 3
	OperatorType_Modulus  OperatorType = 4
	OperatorType_Gt       OperatorType = 5
	OperatorType_Lt       OperatorType = 6
	OperatorType_GtEq     OperatorType = 7
	OperatorType_LtEq     OperatorType = 8
	OperatorType_Eq       OperatorType = 9
	OperatorType_NotEq    OperatorType = 10
	OperatorType_And      OperatorType = 11
	OperatorType_Or       OperatorType = 12
	OperatorType_Not      OperatorType = 13
	OperatorType_Like     OperatorType = 14
	OperatorType_NotLike  OperatorType = 15
	OperatorType_None     OperatorType = 16
)

// Enum value maps for OperatorType.
var (
	OperatorType_name = map[int32]string{
		0:  "Plus",
		1:  "Minus",
		2:  "Multiply",
		3:  "Divide",
		4:  "Modulus",
		5:  "Gt",
		6:  "Lt",
		7:  "GtEq",
		8:  "LtEq",
		9:  "Eq",
		10: "NotEq",
		11: "And",
		12: "Or",
		13: "Not",
		14: "Like",
		15: "NotLike",
		16: "None",
	}
	OperatorType_value = map[string]int32{
		"Plus":     0,
		"Minus":    1,
		"Multiply": 2,
		"Divide":   3,
		"Modulus":  4,
		"Gt":       5,
		"Lt":       6,
		"GtEq":     7,
		"LtEq":     8,
		"Eq":       9,
		"NotEq":    10,
		"And":      11,
		"Or":       12,
		"Not":      13,
		"Like":     14,
		"NotLike":  15,
		"None":     16,
	}
)

func (x OperatorType) Enum() *OperatorType {
	p := new(OperatorType)
	*p = x
	return p
}

func (x OperatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sqlight_proto_enumTypes[0].Descriptor()
}

func (OperatorType) Type() protoreflect.EnumType {
	return &file_proto_sqlight_proto_enumTypes[0]
}

func (x OperatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorType.Descriptor instead.
func (OperatorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{0}
}

type AggType int32

const (
	AggType_UnknownAgg AggType = 0
	AggType_MAX        AggType = 1
	AggType_MIN        AggType = 2
	AggType_COUNT      AggType = 3
	AggType_SUM        AggType = 4
	AggType_AVG        AggType = 5
)

// Enum value maps for AggType.
var (
	AggType_name = map[int32]string{
		0: "UnknownAgg",
		1: "MAX",
		2: "MIN",
		3: "COUNT",
		4: "SUM",
		5: "AVG",
	}
	AggType_value = map[string]int32{
		"UnknownAgg": 0,
		"MAX":        1,
		"MIN":        2,
		"COUNT":      3,
		"SUM":        4,
		"AVG":        5,
	}
)

func (x AggType) Enum() *AggType {
	p := new(AggType)
	*p = x
	return p
}

func (x AggType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sqlight_proto_enumTypes[1].Descriptor()
}

func (AggType) Type() protoreflect.EnumType {
	return &file_proto_sqlight_proto_enumTypes[1]
}

func (x AggType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggType.Descriptor instead.
func (AggType) EnumDescriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{1}
}

type SetOperatorType int32

const (
	SetOperatorType_Union     SetOperatorType = 0
	SetOperatorType_Intersect SetOperatorType = 1
	SetOperatorType_Except    SetOperatorType = 2
)

// Enum value maps for SetOperatorType.
var (
	SetOperatorType_name = map[int32]string{
		0: "Union",
		1: "Intersect",
		2: "Except",
	}
	SetOperatorType_value = map[string]int32{
		"Union":     0,
		"Intersect": 1,
		"Except":    2,
	}
)

func (x SetOperatorType) Enum() *SetOperatorType {
	p := new(SetOperatorType)
	*p = x
	return p
}

func (x SetOperatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetOperatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sqlight_proto_enumTypes[2].Descriptor()
}

func (SetOperatorType) Type() protoreflect.EnumType {
	return &file_proto_sqlight_proto_enumTypes[2]
}

func (x SetOperatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetOperatorType.Descriptor instead.
func (SetOperatorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2}
}

type JoinTypeCondition int32

const (
	JoinTypeCondition_INNER      JoinTypeCondition = 0
	JoinTypeCondition_LEFT       JoinTypeCondition = 1
	JoinTypeCondition_RIGHT      JoinTypeCondition = 2
	JoinTypeCondition_FULL       JoinTypeCondition = 3
	JoinTypeCondition_LEFTOUTER  JoinTypeCondition = 4
	JoinTypeCondition_RIGHTOUTER JoinTypeCondition = 5
	JoinTypeCondition_FULLOUTER  JoinTypeCondition = 6
	JoinTypeCondition_IMPLICIT   JoinTypeCondition = 7
)

// Enum value maps for JoinTypeCondition.
var (
	JoinTypeCondition_name = map[int32]string{
		0: "INNER",
		1: "LEFT",
		2: "RIGHT",
		3: "FULL",
		4: "LEFTOUTER",
		5: "RIGHTOUTER",
		6: "FULLOUTER",
		7: "IMPLICIT",
	}
	JoinTypeCondition_value = map[string]int32{
		"INNER":      0,
		"LEFT":       1,
		"RIGHT":      2,
		"FULL":       3,
		"LEFTOUTER":  4,
		"RIGHTOUTER": 5,
		"FULLOUTER":  6,
		"IMPLICIT":   7,
	}
)

func (x JoinTypeCondition) Enum() *JoinTypeCondition {
	p := new(JoinTypeCondition)
	*p = x
	return p
}

func (x JoinTypeCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinTypeCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sqlight_proto_enumTypes[3].Descriptor()
}

func (JoinTypeCondition) Type() protoreflect.EnumType {
	return &file_proto_sqlight_proto_enumTypes[3]
}

func (x JoinTypeCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinTypeCondition.Descriptor instead.
func (JoinTypeCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{3}
}

type CompoundIdent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idents []string `protobuf:"bytes,1,rep,name=idents,proto3" json:"idents,omitempty"`
}

func (x *CompoundIdent) Reset() {
	*x = CompoundIdent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompoundIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundIdent) ProtoMessage() {}

func (x *CompoundIdent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundIdent.ProtoReflect.Descriptor instead.
func (*CompoundIdent) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{0}
}

func (x *CompoundIdent) GetIdents() []string {
	if x != nil {
		return x.Idents
	}
	return nil
}

type AggFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName AggType          `protobuf:"varint,1,opt,name=typeName,proto3,enum=sqlight.AggType" json:"typeName,omitempty"`
	RestArgs []*CompoundIdent `protobuf:"bytes,2,rep,name=restArgs,proto3" json:"restArgs,omitempty"`
}

func (x *AggFunction) Reset() {
	*x = AggFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggFunction) ProtoMessage() {}

func (x *AggFunction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggFunction.ProtoReflect.Descriptor instead.
func (*AggFunction) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{1}
}

func (x *AggFunction) GetTypeName() AggType {
	if x != nil {
		return x.TypeName
	}
	return AggType_UnknownAgg
}

func (x *AggFunction) GetRestArgs() []*CompoundIdent {
	if x != nil {
		return x.RestArgs
	}
	return nil
}

type QueryStmt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CTEs            []*QueryStmt_CTE            `protobuf:"bytes,2,rep,name=CTEs,proto3" json:"CTEs,omitempty"`
	Body            *QueryStmt_SetOperationExpr `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	OrderBy         []*QueryStmt_OrderByExpr    `protobuf:"bytes,5,rep,name=orderBy,proto3" json:"orderBy,omitempty"`
	LimitExpression *QueryStmt_LimitExpr        `protobuf:"bytes,6,opt,name=limitExpression,proto3" json:"limitExpression,omitempty"`
}

func (x *QueryStmt) Reset() {
	*x = QueryStmt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt) ProtoMessage() {}

func (x *QueryStmt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt.ProtoReflect.Descriptor instead.
func (*QueryStmt) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStmt) GetCTEs() []*QueryStmt_CTE {
	if x != nil {
		return x.CTEs
	}
	return nil
}

func (x *QueryStmt) GetBody() *QueryStmt_SetOperationExpr {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *QueryStmt) GetOrderBy() []*QueryStmt_OrderByExpr {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *QueryStmt) GetLimitExpression() *QueryStmt_LimitExpr {
	if x != nil {
		return x.LimitExpression
	}
	return nil
}

type QueryStmt_CTE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AliasName string     `protobuf:"bytes,1,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
	Query     *QueryStmt `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryStmt_CTE) Reset() {
	*x = QueryStmt_CTE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_CTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_CTE) ProtoMessage() {}

func (x *QueryStmt_CTE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_CTE.ProtoReflect.Descriptor instead.
func (*QueryStmt_CTE) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 0}
}

func (x *QueryStmt_CTE) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *QueryStmt_CTE) GetQuery() *QueryStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryStmt_InSubQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr     *CompoundIdent `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	SubQuery *QueryStmt     `protobuf:"bytes,2,opt,name=subQuery,proto3" json:"subQuery,omitempty"`
	Negated  bool           `protobuf:"varint,3,opt,name=negated,proto3" json:"negated,omitempty"`
}

func (x *QueryStmt_InSubQuery) Reset() {
	*x = QueryStmt_InSubQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_InSubQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_InSubQuery) ProtoMessage() {}

func (x *QueryStmt_InSubQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_InSubQuery.ProtoReflect.Descriptor instead.
func (*QueryStmt_InSubQuery) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 1}
}

func (x *QueryStmt_InSubQuery) GetExpr() *CompoundIdent {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *QueryStmt_InSubQuery) GetSubQuery() *QueryStmt {
	if x != nil {
		return x.SubQuery
	}
	return nil
}

func (x *QueryStmt_InSubQuery) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

type QueryStmt_BinaryExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to LeftOneOf:
	//	*QueryStmt_BinaryExpr_LeftIdents
	//	*QueryStmt_BinaryExpr_LeftBinary
	LeftOneOf isQueryStmt_BinaryExpr_LeftOneOf `protobuf_oneof:"LeftOneOf"`
	Op        OperatorType                     `protobuf:"varint,3,opt,name=op,proto3,enum=sqlight.OperatorType" json:"op,omitempty"`
	// Types that are assignable to RightOneOf:
	//	*QueryStmt_BinaryExpr_RightIdents
	//	*QueryStmt_BinaryExpr_RightBinary
	//	*QueryStmt_BinaryExpr_QueryValue
	//	*QueryStmt_BinaryExpr_SingleQuotedString
	//	*QueryStmt_BinaryExpr_DoubleValue
	//	*QueryStmt_BinaryExpr_LongValue
	RightOneOf isQueryStmt_BinaryExpr_RightOneOf `protobuf_oneof:"RightOneOf"`
}

func (x *QueryStmt_BinaryExpr) Reset() {
	*x = QueryStmt_BinaryExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_BinaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_BinaryExpr) ProtoMessage() {}

func (x *QueryStmt_BinaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_BinaryExpr.ProtoReflect.Descriptor instead.
func (*QueryStmt_BinaryExpr) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 2}
}

func (m *QueryStmt_BinaryExpr) GetLeftOneOf() isQueryStmt_BinaryExpr_LeftOneOf {
	if m != nil {
		return m.LeftOneOf
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetLeftIdents() *CompoundIdent {
	if x, ok := x.GetLeftOneOf().(*QueryStmt_BinaryExpr_LeftIdents); ok {
		return x.LeftIdents
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetLeftBinary() *QueryStmt_BinaryExpr {
	if x, ok := x.GetLeftOneOf().(*QueryStmt_BinaryExpr_LeftBinary); ok {
		return x.LeftBinary
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetOp() OperatorType {
	if x != nil {
		return x.Op
	}
	return OperatorType_Plus
}

func (m *QueryStmt_BinaryExpr) GetRightOneOf() isQueryStmt_BinaryExpr_RightOneOf {
	if m != nil {
		return m.RightOneOf
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetRightIdents() *CompoundIdent {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_RightIdents); ok {
		return x.RightIdents
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetRightBinary() *QueryStmt_BinaryExpr {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_RightBinary); ok {
		return x.RightBinary
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetQueryValue() *QueryStmt_InSubQuery {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_QueryValue); ok {
		return x.QueryValue
	}
	return nil
}

func (x *QueryStmt_BinaryExpr) GetSingleQuotedString() string {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_SingleQuotedString); ok {
		return x.SingleQuotedString
	}
	return ""
}

func (x *QueryStmt_BinaryExpr) GetDoubleValue() float64 {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *QueryStmt_BinaryExpr) GetLongValue() int64 {
	if x, ok := x.GetRightOneOf().(*QueryStmt_BinaryExpr_LongValue); ok {
		return x.LongValue
	}
	return 0
}

type isQueryStmt_BinaryExpr_LeftOneOf interface {
	isQueryStmt_BinaryExpr_LeftOneOf()
}

type QueryStmt_BinaryExpr_LeftIdents struct {
	LeftIdents *CompoundIdent `protobuf:"bytes,1,opt,name=leftIdents,proto3,oneof"`
}

type QueryStmt_BinaryExpr_LeftBinary struct {
	LeftBinary *QueryStmt_BinaryExpr `protobuf:"bytes,2,opt,name=leftBinary,proto3,oneof"`
}

func (*QueryStmt_BinaryExpr_LeftIdents) isQueryStmt_BinaryExpr_LeftOneOf() {}

func (*QueryStmt_BinaryExpr_LeftBinary) isQueryStmt_BinaryExpr_LeftOneOf() {}

type isQueryStmt_BinaryExpr_RightOneOf interface {
	isQueryStmt_BinaryExpr_RightOneOf()
}

type QueryStmt_BinaryExpr_RightIdents struct {
	RightIdents *CompoundIdent `protobuf:"bytes,4,opt,name=rightIdents,proto3,oneof"`
}

type QueryStmt_BinaryExpr_RightBinary struct {
	RightBinary *QueryStmt_BinaryExpr `protobuf:"bytes,5,opt,name=rightBinary,proto3,oneof"`
}

type QueryStmt_BinaryExpr_QueryValue struct {
	QueryValue *QueryStmt_InSubQuery `protobuf:"bytes,6,opt,name=queryValue,proto3,oneof"`
}

type QueryStmt_BinaryExpr_SingleQuotedString struct {
	SingleQuotedString string `protobuf:"bytes,7,opt,name=singleQuotedString,proto3,oneof"`
}

type QueryStmt_BinaryExpr_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,8,opt,name=doubleValue,proto3,oneof"`
}

type QueryStmt_BinaryExpr_LongValue struct {
	LongValue int64 `protobuf:"varint,9,opt,name=longValue,proto3,oneof"`
}

func (*QueryStmt_BinaryExpr_RightIdents) isQueryStmt_BinaryExpr_RightOneOf() {}

func (*QueryStmt_BinaryExpr_RightBinary) isQueryStmt_BinaryExpr_RightOneOf() {}

func (*QueryStmt_BinaryExpr_QueryValue) isQueryStmt_BinaryExpr_RightOneOf() {}

func (*QueryStmt_BinaryExpr_SingleQuotedString) isQueryStmt_BinaryExpr_RightOneOf() {}

func (*QueryStmt_BinaryExpr_DoubleValue) isQueryStmt_BinaryExpr_RightOneOf() {}

func (*QueryStmt_BinaryExpr_LongValue) isQueryStmt_BinaryExpr_RightOneOf() {}

type QueryStmt_SQLSelect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistinctBool bool                                 `protobuf:"varint,1,opt,name=distinctBool,proto3" json:"distinctBool,omitempty"`
	Projection   []*QueryStmt_SQLSelect_SQLSelectItem `protobuf:"bytes,2,rep,name=projection,proto3" json:"projection,omitempty"`
	FromClause   []*QueryStmt_SQLSelect_QualifiedJoin `protobuf:"bytes,3,rep,name=fromClause,proto3" json:"fromClause,omitempty"`
	// Types that are assignable to WhereClause:
	//	*QueryStmt_SQLSelect_InQuery
	//	*QueryStmt_SQLSelect_BinExpr
	WhereClause   isQueryStmt_SQLSelect_WhereClause `protobuf_oneof:"WhereClause"`
	GroupByClause []*CompoundIdent                  `protobuf:"bytes,8,rep,name=groupByClause,proto3" json:"groupByClause,omitempty"`
	HavingClause  *QueryStmt_BinaryExpr             `protobuf:"bytes,9,opt,name=havingClause,proto3" json:"havingClause,omitempty"`
}

func (x *QueryStmt_SQLSelect) Reset() {
	*x = QueryStmt_SQLSelect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_SQLSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_SQLSelect) ProtoMessage() {}

func (x *QueryStmt_SQLSelect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_SQLSelect.ProtoReflect.Descriptor instead.
func (*QueryStmt_SQLSelect) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 3}
}

func (x *QueryStmt_SQLSelect) GetDistinctBool() bool {
	if x != nil {
		return x.DistinctBool
	}
	return false
}

func (x *QueryStmt_SQLSelect) GetProjection() []*QueryStmt_SQLSelect_SQLSelectItem {
	if x != nil {
		return x.Projection
	}
	return nil
}

func (x *QueryStmt_SQLSelect) GetFromClause() []*QueryStmt_SQLSelect_QualifiedJoin {
	if x != nil {
		return x.FromClause
	}
	return nil
}

func (m *QueryStmt_SQLSelect) GetWhereClause() isQueryStmt_SQLSelect_WhereClause {
	if m != nil {
		return m.WhereClause
	}
	return nil
}

func (x *QueryStmt_SQLSelect) GetInQuery() *QueryStmt_InSubQuery {
	if x, ok := x.GetWhereClause().(*QueryStmt_SQLSelect_InQuery); ok {
		return x.InQuery
	}
	return nil
}

func (x *QueryStmt_SQLSelect) GetBinExpr() *QueryStmt_BinaryExpr {
	if x, ok := x.GetWhereClause().(*QueryStmt_SQLSelect_BinExpr); ok {
		return x.BinExpr
	}
	return nil
}

func (x *QueryStmt_SQLSelect) GetGroupByClause() []*CompoundIdent {
	if x != nil {
		return x.GroupByClause
	}
	return nil
}

func (x *QueryStmt_SQLSelect) GetHavingClause() *QueryStmt_BinaryExpr {
	if x != nil {
		return x.HavingClause
	}
	return nil
}

type isQueryStmt_SQLSelect_WhereClause interface {
	isQueryStmt_SQLSelect_WhereClause()
}

type QueryStmt_SQLSelect_InQuery struct {
	InQuery *QueryStmt_InSubQuery `protobuf:"bytes,4,opt,name=inQuery,proto3,oneof"`
}

type QueryStmt_SQLSelect_BinExpr struct {
	BinExpr *QueryStmt_BinaryExpr `protobuf:"bytes,5,opt,name=binExpr,proto3,oneof"`
}

func (*QueryStmt_SQLSelect_InQuery) isQueryStmt_SQLSelect_WhereClause() {}

func (*QueryStmt_SQLSelect_BinExpr) isQueryStmt_SQLSelect_WhereClause() {}

type QueryStmt_SetOperationExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftSide  *QueryStmt_SQLSelect        `protobuf:"bytes,1,opt,name=leftSide,proto3" json:"leftSide,omitempty"`
	AllBool   bool                        `protobuf:"varint,2,opt,name=allBool,proto3" json:"allBool,omitempty"`
	Op        SetOperatorType             `protobuf:"varint,3,opt,name=op,proto3,enum=sqlight.SetOperatorType" json:"op,omitempty"`
	RightSide *QueryStmt_SetOperationExpr `protobuf:"bytes,4,opt,name=rightSide,proto3" json:"rightSide,omitempty"`
}

func (x *QueryStmt_SetOperationExpr) Reset() {
	*x = QueryStmt_SetOperationExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_SetOperationExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_SetOperationExpr) ProtoMessage() {}

func (x *QueryStmt_SetOperationExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_SetOperationExpr.ProtoReflect.Descriptor instead.
func (*QueryStmt_SetOperationExpr) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 4}
}

func (x *QueryStmt_SetOperationExpr) GetLeftSide() *QueryStmt_SQLSelect {
	if x != nil {
		return x.LeftSide
	}
	return nil
}

func (x *QueryStmt_SetOperationExpr) GetAllBool() bool {
	if x != nil {
		return x.AllBool
	}
	return false
}

func (x *QueryStmt_SetOperationExpr) GetOp() SetOperatorType {
	if x != nil {
		return x.Op
	}
	return SetOperatorType_Union
}

func (x *QueryStmt_SetOperationExpr) GetRightSide() *QueryStmt_SetOperationExpr {
	if x != nil {
		return x.RightSide
	}
	return nil
}

type QueryStmt_OrderByExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr    *CompoundIdent `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	ASCBool bool           `protobuf:"varint,3,opt,name=aSCBool,proto3" json:"aSCBool,omitempty"`
}

func (x *QueryStmt_OrderByExpr) Reset() {
	*x = QueryStmt_OrderByExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_OrderByExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_OrderByExpr) ProtoMessage() {}

func (x *QueryStmt_OrderByExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_OrderByExpr.ProtoReflect.Descriptor instead.
func (*QueryStmt_OrderByExpr) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 5}
}

func (x *QueryStmt_OrderByExpr) GetExpr() *CompoundIdent {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *QueryStmt_OrderByExpr) GetASCBool() bool {
	if x != nil {
		return x.ASCBool
	}
	return false
}

type QueryStmt_LimitExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllBool     bool  `protobuf:"varint,1,opt,name=allBool,proto3" json:"allBool,omitempty"`
	LimitValue  int64 `protobuf:"varint,4,opt,name=limitValue,proto3" json:"limitValue,omitempty"`
	OffsetValue int64 `protobuf:"varint,5,opt,name=offsetValue,proto3" json:"offsetValue,omitempty"`
}

func (x *QueryStmt_LimitExpr) Reset() {
	*x = QueryStmt_LimitExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_LimitExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_LimitExpr) ProtoMessage() {}

func (x *QueryStmt_LimitExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_LimitExpr.ProtoReflect.Descriptor instead.
func (*QueryStmt_LimitExpr) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 6}
}

func (x *QueryStmt_LimitExpr) GetAllBool() bool {
	if x != nil {
		return x.AllBool
	}
	return false
}

func (x *QueryStmt_LimitExpr) GetLimitValue() int64 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *QueryStmt_LimitExpr) GetOffsetValue() int64 {
	if x != nil {
		return x.OffsetValue
	}
	return 0
}

type QueryStmt_SQLSelect_SQLSelectItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldFunction *AggFunction   `protobuf:"bytes,1,opt,name=fieldFunction,proto3" json:"fieldFunction,omitempty"`
	FieldIdents   *CompoundIdent `protobuf:"bytes,2,opt,name=fieldIdents,proto3" json:"fieldIdents,omitempty"`
	AliasName     string         `protobuf:"bytes,3,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
}

func (x *QueryStmt_SQLSelect_SQLSelectItem) Reset() {
	*x = QueryStmt_SQLSelect_SQLSelectItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_SQLSelect_SQLSelectItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_SQLSelect_SQLSelectItem) ProtoMessage() {}

func (x *QueryStmt_SQLSelect_SQLSelectItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_SQLSelect_SQLSelectItem.ProtoReflect.Descriptor instead.
func (*QueryStmt_SQLSelect_SQLSelectItem) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 3, 0}
}

func (x *QueryStmt_SQLSelect_SQLSelectItem) GetFieldFunction() *AggFunction {
	if x != nil {
		return x.FieldFunction
	}
	return nil
}

func (x *QueryStmt_SQLSelect_SQLSelectItem) GetFieldIdents() *CompoundIdent {
	if x != nil {
		return x.FieldIdents
	}
	return nil
}

func (x *QueryStmt_SQLSelect_SQLSelectItem) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

type QueryStmt_SQLSelect_QualifiedJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          *CompoundIdent                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AliasName     string                             `protobuf:"bytes,2,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
	LeftElement   *QueryStmt_SQLSelect_QualifiedJoin `protobuf:"bytes,3,opt,name=leftElement,proto3" json:"leftElement,omitempty"`
	TypeCondition JoinTypeCondition                  `protobuf:"varint,4,opt,name=typeCondition,proto3,enum=sqlight.JoinTypeCondition" json:"typeCondition,omitempty"`
	Spec          *QueryStmt_BinaryExpr              `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) Reset() {
	*x = QueryStmt_SQLSelect_QualifiedJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sqlight_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStmt_SQLSelect_QualifiedJoin) ProtoMessage() {}

func (x *QueryStmt_SQLSelect_QualifiedJoin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlight_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStmt_SQLSelect_QualifiedJoin.ProtoReflect.Descriptor instead.
func (*QueryStmt_SQLSelect_QualifiedJoin) Descriptor() ([]byte, []int) {
	return file_proto_sqlight_proto_rawDescGZIP(), []int{2, 3, 1}
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) GetName() *CompoundIdent {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) GetLeftElement() *QueryStmt_SQLSelect_QualifiedJoin {
	if x != nil {
		return x.LeftElement
	}
	return nil
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) GetTypeCondition() JoinTypeCondition {
	if x != nil {
		return x.TypeCondition
	}
	return JoinTypeCondition_INNER
}

func (x *QueryStmt_SQLSelect_QualifiedJoin) GetSpec() *QueryStmt_BinaryExpr {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_proto_sqlight_proto protoreflect.FileDescriptor

var file_proto_sqlight_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x27,
	0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6f, 0x0a, 0x0b, 0x41, 0x67, 0x67, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x2e, 0x41, 0x67, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x22, 0xf1, 0x11, 0x0a, 0x09, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x43, 0x54, 0x45, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x43, 0x54, 0x45, 0x52, 0x04, 0x43, 0x54,
	0x45, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x6d, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x78, 0x70, 0x72, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x38, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73,
	0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x45, 0x78, 0x70, 0x72, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x46, 0x0a, 0x0f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x6d, 0x74, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x45, 0x78, 0x70, 0x72, 0x52, 0x0f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x4d, 0x0a,
	0x03, 0x43, 0x54, 0x45, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x6d, 0x74, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x82, 0x01, 0x0a,
	0x0a, 0x49, 0x6e, 0x53, 0x75, 0x62, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x65,
	0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x71, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x52, 0x08, 0x73,
	0x75, 0x62, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x64, 0x1a, 0xff, 0x03, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72,
	0x12, 0x38, 0x0a, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a,
	0x6c, 0x65, 0x66, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x6c, 0x65,
	0x66, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x6d, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52,
	0x0a, 0x6c, 0x65, 0x66, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x48,
	0x01, 0x52, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x41,
	0x0a, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78,
	0x70, 0x72, 0x48, 0x01, 0x52, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x12, 0x3f, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x49, 0x6e, 0x53, 0x75, 0x62, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x48, 0x01, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x30, 0x0a, 0x12, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x12, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x4c, 0x65, 0x66, 0x74,
	0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x42, 0x0c, 0x0a, 0x0a, 0x52, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x6e,
	0x65, 0x4f, 0x66, 0x1a, 0x92, 0x07, 0x0a, 0x09, 0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x42, 0x6f, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63,
	0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x4a, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x71, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x53, 0x51,
	0x4c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x4a, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x07, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x6d, 0x74, 0x2e, 0x49, 0x6e, 0x53, 0x75, 0x62, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52,
	0x07, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x45,
	0x78, 0x70, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x45,
	0x78, 0x70, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x43, 0x6c,
	0x61, 0x75, 0x73, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x43, 0x6c, 0x61, 0x75, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0c, 0x68, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x43, 0x6c, 0x61, 0x75, 0x73,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x52, 0x0c, 0x68, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x43, 0x6c,
	0x61, 0x75, 0x73, 0x65, 0x1a, 0xa3, 0x01, 0x0a, 0x0d, 0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3a, 0x0a, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x41, 0x67, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x52,
	0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x9c, 0x02, 0x0a, 0x0d, 0x51,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x6c, 0x65, 0x66, 0x74, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x71,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e,
	0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x0b, 0x6c, 0x65, 0x66, 0x74, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x71,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6d, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45,
	0x78, 0x70, 0x72, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x42, 0x0d, 0x0a, 0x0b, 0x57, 0x68, 0x65,
	0x72, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x1a, 0xd3, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x74,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x72, 0x12, 0x38, 0x0a,
	0x08, 0x6c, 0x65, 0x66, 0x74, 0x53, 0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x74, 0x6d, 0x74, 0x2e, 0x53, 0x51, 0x4c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x08, 0x6c,
	0x65, 0x66, 0x74, 0x53, 0x69, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x42, 0x6f,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x28, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x41, 0x0a, 0x09, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x53, 0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x73, 0x71, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x6d, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x78, 0x70, 0x72, 0x52, 0x09, 0x72, 0x69, 0x67, 0x68, 0x74, 0x53, 0x69, 0x64, 0x65, 0x1a, 0x53,
	0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x45, 0x78, 0x70, 0x72, 0x12, 0x2a, 0x0a,
	0x04, 0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x71,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x53, 0x43,
	0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x53, 0x43, 0x42,
	0x6f, 0x6f, 0x6c, 0x1a, 0x67, 0x0a, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x45, 0x78, 0x70, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0xbc, 0x01, 0x0a,
	0x0c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x6c, 0x75, 0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x75, 0x73,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x75, 0x73, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x74, 0x10,
	0x05, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x74, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x74, 0x45,
	0x71, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x74, 0x45, 0x71, 0x10, 0x08, 0x12, 0x06, 0x0a,
	0x02, 0x45, 0x71, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x10, 0x0a,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x6e, 0x64, 0x10, 0x0b, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x72, 0x10,
	0x0c, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x6f, 0x74, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x69,
	0x6b, 0x65, 0x10, 0x0e, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x10,
	0x0f, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x10, 0x2a, 0x48, 0x0a, 0x07, 0x41,
	0x67, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x41, 0x67, 0x67, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x58, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x4d, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03,
	0x41, 0x56, 0x47, 0x10, 0x05, 0x2a, 0x37, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x6e, 0x69, 0x6f,
	0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x10, 0x02, 0x2a, 0x79,
	0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x03, 0x12, 0x0d, 0x0a,
	0x09, 0x4c, 0x45, 0x46, 0x54, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a,
	0x52, 0x49, 0x47, 0x48, 0x54, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09,
	0x46, 0x55, 0x4c, 0x4c, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4d, 0x50, 0x4c, 0x49, 0x43, 0x49, 0x54, 0x10, 0x07, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x78,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sqlight_proto_rawDescOnce sync.Once
	file_proto_sqlight_proto_rawDescData = file_proto_sqlight_proto_rawDesc
)

func file_proto_sqlight_proto_rawDescGZIP() []byte {
	file_proto_sqlight_proto_rawDescOnce.Do(func() {
		file_proto_sqlight_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sqlight_proto_rawDescData)
	})
	return file_proto_sqlight_proto_rawDescData
}

var file_proto_sqlight_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_sqlight_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_sqlight_proto_goTypes = []interface{}{
	(OperatorType)(0),                         // 0: sqlight.OperatorType
	(AggType)(0),                              // 1: sqlight.AggType
	(SetOperatorType)(0),                      // 2: sqlight.SetOperatorType
	(JoinTypeCondition)(0),                    // 3: sqlight.JoinTypeCondition
	(*CompoundIdent)(nil),                     // 4: sqlight.CompoundIdent
	(*AggFunction)(nil),                       // 5: sqlight.AggFunction
	(*QueryStmt)(nil),                         // 6: sqlight.QueryStmt
	(*QueryStmt_CTE)(nil),                     // 7: sqlight.QueryStmt.CTE
	(*QueryStmt_InSubQuery)(nil),              // 8: sqlight.QueryStmt.InSubQuery
	(*QueryStmt_BinaryExpr)(nil),              // 9: sqlight.QueryStmt.BinaryExpr
	(*QueryStmt_SQLSelect)(nil),               // 10: sqlight.QueryStmt.SQLSelect
	(*QueryStmt_SetOperationExpr)(nil),        // 11: sqlight.QueryStmt.SetOperationExpr
	(*QueryStmt_OrderByExpr)(nil),             // 12: sqlight.QueryStmt.OrderByExpr
	(*QueryStmt_LimitExpr)(nil),               // 13: sqlight.QueryStmt.LimitExpr
	(*QueryStmt_SQLSelect_SQLSelectItem)(nil), // 14: sqlight.QueryStmt.SQLSelect.SQLSelectItem
	(*QueryStmt_SQLSelect_QualifiedJoin)(nil), // 15: sqlight.QueryStmt.SQLSelect.QualifiedJoin
}
var file_proto_sqlight_proto_depIdxs = []int32{
	1,  // 0: sqlight.AggFunction.typeName:type_name -> sqlight.AggType
	4,  // 1: sqlight.AggFunction.restArgs:type_name -> sqlight.CompoundIdent
	7,  // 2: sqlight.QueryStmt.CTEs:type_name -> sqlight.QueryStmt.CTE
	11, // 3: sqlight.QueryStmt.body:type_name -> sqlight.QueryStmt.SetOperationExpr
	12, // 4: sqlight.QueryStmt.orderBy:type_name -> sqlight.QueryStmt.OrderByExpr
	13, // 5: sqlight.QueryStmt.limitExpression:type_name -> sqlight.QueryStmt.LimitExpr
	6,  // 6: sqlight.QueryStmt.CTE.query:type_name -> sqlight.QueryStmt
	4,  // 7: sqlight.QueryStmt.InSubQuery.expr:type_name -> sqlight.CompoundIdent
	6,  // 8: sqlight.QueryStmt.InSubQuery.subQuery:type_name -> sqlight.QueryStmt
	4,  // 9: sqlight.QueryStmt.BinaryExpr.leftIdents:type_name -> sqlight.CompoundIdent
	9,  // 10: sqlight.QueryStmt.BinaryExpr.leftBinary:type_name -> sqlight.QueryStmt.BinaryExpr
	0,  // 11: sqlight.QueryStmt.BinaryExpr.op:type_name -> sqlight.OperatorType
	4,  // 12: sqlight.QueryStmt.BinaryExpr.rightIdents:type_name -> sqlight.CompoundIdent
	9,  // 13: sqlight.QueryStmt.BinaryExpr.rightBinary:type_name -> sqlight.QueryStmt.BinaryExpr
	8,  // 14: sqlight.QueryStmt.BinaryExpr.queryValue:type_name -> sqlight.QueryStmt.InSubQuery
	14, // 15: sqlight.QueryStmt.SQLSelect.projection:type_name -> sqlight.QueryStmt.SQLSelect.SQLSelectItem
	15, // 16: sqlight.QueryStmt.SQLSelect.fromClause:type_name -> sqlight.QueryStmt.SQLSelect.QualifiedJoin
	8,  // 17: sqlight.QueryStmt.SQLSelect.inQuery:type_name -> sqlight.QueryStmt.InSubQuery
	9,  // 18: sqlight.QueryStmt.SQLSelect.binExpr:type_name -> sqlight.QueryStmt.BinaryExpr
	4,  // 19: sqlight.QueryStmt.SQLSelect.groupByClause:type_name -> sqlight.CompoundIdent
	9,  // 20: sqlight.QueryStmt.SQLSelect.havingClause:type_name -> sqlight.QueryStmt.BinaryExpr
	10, // 21: sqlight.QueryStmt.SetOperationExpr.leftSide:type_name -> sqlight.QueryStmt.SQLSelect
	2,  // 22: sqlight.QueryStmt.SetOperationExpr.op:type_name -> sqlight.SetOperatorType
	11, // 23: sqlight.QueryStmt.SetOperationExpr.rightSide:type_name -> sqlight.QueryStmt.SetOperationExpr
	4,  // 24: sqlight.QueryStmt.OrderByExpr.expr:type_name -> sqlight.CompoundIdent
	5,  // 25: sqlight.QueryStmt.SQLSelect.SQLSelectItem.fieldFunction:type_name -> sqlight.AggFunction
	4,  // 26: sqlight.QueryStmt.SQLSelect.SQLSelectItem.fieldIdents:type_name -> sqlight.CompoundIdent
	4,  // 27: sqlight.QueryStmt.SQLSelect.QualifiedJoin.name:type_name -> sqlight.CompoundIdent
	15, // 28: sqlight.QueryStmt.SQLSelect.QualifiedJoin.leftElement:type_name -> sqlight.QueryStmt.SQLSelect.QualifiedJoin
	3,  // 29: sqlight.QueryStmt.SQLSelect.QualifiedJoin.typeCondition:type_name -> sqlight.JoinTypeCondition
	9,  // 30: sqlight.QueryStmt.SQLSelect.QualifiedJoin.spec:type_name -> sqlight.QueryStmt.BinaryExpr
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_sqlight_proto_init() }
func file_proto_sqlight_proto_init() {
	if File_proto_sqlight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sqlight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompoundIdent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_CTE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_InSubQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_BinaryExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_SQLSelect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_SetOperationExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_OrderByExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_LimitExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_SQLSelect_SQLSelectItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sqlight_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStmt_SQLSelect_QualifiedJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_sqlight_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*QueryStmt_BinaryExpr_LeftIdents)(nil),
		(*QueryStmt_BinaryExpr_LeftBinary)(nil),
		(*QueryStmt_BinaryExpr_RightIdents)(nil),
		(*QueryStmt_BinaryExpr_RightBinary)(nil),
		(*QueryStmt_BinaryExpr_QueryValue)(nil),
		(*QueryStmt_BinaryExpr_SingleQuotedString)(nil),
		(*QueryStmt_BinaryExpr_DoubleValue)(nil),
		(*QueryStmt_BinaryExpr_LongValue)(nil),
	}
	file_proto_sqlight_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*QueryStmt_SQLSelect_InQuery)(nil),
		(*QueryStmt_SQLSelect_BinExpr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sqlight_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sqlight_proto_goTypes,
		DependencyIndexes: file_proto_sqlight_proto_depIdxs,
		EnumInfos:         file_proto_sqlight_proto_enumTypes,
		MessageInfos:      file_proto_sqlight_proto_msgTypes,
	}.Build()
	File_proto_sqlight_proto = out.File
	file_proto_sqlight_proto_rawDesc = nil
	file_proto_sqlight_proto_goTypes = nil
	file_proto_sqlight_proto_depIdxs = nil
}
